export const ENTITY_CONSTANTS = {
  ENTITY_OFFSET_PREPARE: 'entity/ENTITY_OFFSET_PREPARE',
  ENTITY_OFFSET_SET: 'entity/ENTITY_OFFSET_SET',
};

export const TILE_CONSTANTS = {
  TILE_SELECT: 'tile/TILE_SELECT',
};

export const PLAYER_CONSTANTS = {
  PLAYER_POSITION_SET: 'player/PLAYER_POSITION_SET'
};

export const GAME_MENU_CONSTANTS = {
  PERSPECTIVE_TOGGLE: 'gameMenu/PERSPECTIVE_TOGGLE'
};
