export const ENTITY_CONSTANTS = {
  ENTITY_OFFSET_PREPARE: 'entity/ENTITY_OFFSET_PREPARE',
  ENTITY_OFFSET_SET: 'entity/ENTITY_OFFSET_SET',
  ENTITY_SIZE_SET: 'entity/ENTITY_SIZE_SET'
};

export const TILE_CONSTANTS = {
  TILE_POSITION_SET: 'tile/TILE_POSITION_SET',
  TILE_SELECT: 'tile/TILE_SELECT',
  TILE_SIZE_SET: 'tile/TILE_SIZE_SET'
};

export const GAME_MENU_CONSTANTS = {
  PERSPECTIVE_TOGGLE: 'gameMenu/PERSPECTIVE_TOGGLE'
};