export const ENTITY_CONSTANTS = {
  ENTITY_OFFSET_PREPARE: 'entity/ENTITY_OFFSET_PREPARE',
  ENTITY_OFFSET_SET: 'entity/ENTITY_OFFSET_SET',
  ENTITY_SIZE_SET: 'entity/ENTITY_SIZE_SET',
  ENTITY_SHOW_ROUTE: 'entity/ENTITY_SHOW_ROUTE',
  ENTITY_FOLLOW_PATH: 'entity/ENTITY_FOLLOW_PATH',
};

export const TILE_CONSTANTS = {
  TILE_POSITION_SET: 'tile/TILE_POSITION_SET',
  TILE_SELECT: 'tile/TILE_SELECT',
  TILE_SIZE_SET: 'tile/TILE_SIZE_SET',
  TILE_CLASS_SET: 'tile/TILE_CLASS_SET',
  TILE_HIGHLIGHT: 'tile/TILE_HIGHLIGHT',
  TILE_DEFAULT_CLASS: 'tile',
};

export const PLAYER_CONSTANTS = {
  PLAYER_POSITION_SET: 'player/PLAYER_POSITION_SET',
  PLAYER_MOVE_TO_POSITION: 'player/PLAYER_MOVE_TO_POSITION',
};

export const GAME_MENU_CONSTANTS = {
  PERSPECTIVE_TOGGLE: 'gameMenu/PERSPECTIVE_TOGGLE',
};
